BlackGeo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('accounting/', include('accounting.urls')),
    url('drawing-solution/', include('drawingSolutions.urls')),
    url('drawing/', include('drawingProblems.urls', 'drawing')),
    url('set/', include('setManager.urls', namespace='sets')),
    url('home/', include('homeService.urls')),
]

setManager/urls.py
from django.conf.urls import url
from django.urls import path

from setManager import views

app_name = 'sets'

urlpatterns = [
    url('new/', views.new_set, name='new'),
    path('delete/<int:set_id>/', views.delete_set, name='delete'),
    path('<int:set_id>/', views.problemSet_page, name='page')
]

templates/home/home-base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css"/>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>



    {% block home-head %}
    {% endblock %}

    {% load static %}

    <link rel="stylesheet" href="{% static 'accounting/base/form.css' %}">

    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>#}

    {% include 'dynamic-background/head.html' %}

    {% include 'home/top-navbar/head.html' %}


    <style>
        html, body {
            margin: 0;
            height: 100%;
            width: 100%;
            background-color: #2e2e6b;
        }

        body {
            display: flex;
            justify-content: center;
            align-content: center;
            min-height: 100%;
            min-height: 100%;
            height: fit-content;
        }


    </style>


</head>
<body>

{% include 'dynamic-background/body.html' %}

{% include 'home/top-navbar/body.html' %}

{% block home-body %}
{% endblock %}

</body>
</html>

templates/home/home.html
{% extends 'home/home-base.html' %}

{% block home-head %}
    <title>Home</title>
{% endblock %}

{% block home-body %}

    <div style="z-index: 10">
        <br>
        <br>
        <br>
        <a href="{% url 'sets:new' %}"><i class="plus massive green icon"></i></a>
        <table class="ui five column table">
            <tbody>
            {% for set in sets %}
                <tr>
                    <td>{{ set.title }}</td>
                    <td><a href="{% url 'sets:page' set.id %}"><i class="eye big white icon"></i></a></td>
                    <td><a href="{% url 'sets:delete' set.id %}"><i class="cancel big white icon"></i></a></td>
                    <td>Male</td>
                    <td>None</td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>

{% endblock %}